apiVersion: apps/v1
kind: Deployment
metadata:
  name: qalb-service
  labels:
    app: qalb-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qalb-service
  template:
    metadata:
      labels:
        app: qalb-service
    spec:
      containers:
        - name: qalb-service
          image: qalb-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://postgres:5432/postgres
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
            - name: SPRING_ELASTICSEARCH_URIS
              value: http://elasticsearch:9200
            - name: SPRING_ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secrets
                  key: username
            - name: SPRING_ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secrets
                  key: password
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
