apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  username: cG9zdGdyZXM= # postgres (base64 encoded)
  password: cG9zdGdyZXM= # postgres (base64 encoded)
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-secrets
type: Opaque
data:
  username: YWRtaW4= # admin (base64 encoded)
  password: U2FpZGp1bWF5ZXYxOTk4MDgyOA== # Saidjumayev19980828 (base64 encoded)
