name: Android CI

on:
  push:
    branches: [ "dev-adk" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CONTABO_SSH_PRIVATE_KEY }}

      - name: Add remote server to known_hosts
        run: |
          ssh-keyscan ${{CONTABO_SSH_USER}}@${{CONTABO_SSH_SERVER}} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh ${{CONTABO_SSH_USER}}@${{CONTABO_SSH_SERVER}} << 'EOF'
          cd ${{CONTABO_PROJECT_PATH}}
          ./runner.sh  
          EOF