name: Deploy to Dev Server

# Trigger the workflow on push events to the 'dev' branch
on:
  push:
    branches:
      - dev # Change this if your development branch has a different name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory
            echo "Checking project directory..."
            if [ ! -d "/var/www/qalb-service" ]; then
              echo "Directory doesn't exist, creating..."
              mkdir -p /var/www/qalb-service
            fi

            cd /var/www/qalb-service

            # Check if this is a git repository
            if [ ! -d ".git" ]; then
              echo "Not a git repository, initializing..."
              rm -rf * .[^.]*  # Clean directory if it exists but isn't a git repo
              git clone https://github.com/Qalb-uz/qalb-service.git .
              if [ $? -ne 0 ]; then
                echo "Failed to clone repository. Trying with organization name..."
                git clone https://github.com/Qalb-uz/qalb-service.git .
                if [ $? -ne 0 ]; then
                  echo "Failed to clone repository. Please check repository URL and permissions."
                  exit 1
                fi
              fi
            fi

            # Make sure we're on dev branch
            git checkout dev

            # Pull latest changes
            echo "Pulling latest changes..."
            git pull origin dev

            # Verify files exist
            echo "Verifying necessary files..."
            if [ ! -f "Dockerfile" ]; then
              echo "ERROR: Dockerfile missing!"
              echo "Current files:"
              ls -la
              exit 1
            fi

            if [ ! -f "docker-compose.yml" ] && [ ! -f "docker-compose.yaml" ]; then
              echo "ERROR: docker-compose.yml missing!"
              echo "Current files:"
              ls -la
              exit 1
            fi

            # Build Docker image
            echo "Building Docker image..."
            docker build --platform linux/amd64 -t tenxegineer/qalb-service:dev .

            # Get current container ID if it exists
            CURRENT_CONTAINER=$(docker ps --filter "name=qalb-service" -q)

            # Start new container with docker-compose
            echo "Starting container..."
            docker-compose up -d

            # Wait for new container to be ready
            echo "Waiting for container to be ready..."
            sleep 10

            # Verify container is running
            NEW_CONTAINER=$(docker ps --filter "name=qalb-service" -q)
            if [ -z "$NEW_CONTAINER" ]; then
              echo "Container failed to start"
              docker ps
              docker-compose logs
              exit 1
            fi

            # Verify service is responding (adjust URL as needed)
            echo "Verifying service is responding..."
            curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/health || echo "Service not responding on expected port, manual verification required"

            # Clean up
            echo "Cleaning up..."
            docker image prune -f

            echo "==================== DEPLOYMENT SUMMARY ===================="
            echo "Git branch: $(git branch --show-current)"
            echo "Git commit: $(git rev-parse HEAD)"
            echo "Docker containers:"
            docker ps
            echo "==================== DEPLOYMENT COMPLETE ===================="
