name: Android CI

on:
  push:
    branches: [ "dev-adk" ]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CONTABO_SSH_SERVER }}
          username: ${{ secrets.CONTABO_SSH_USER }}
          key: ${{ secrets.CONTABO_SSH_PRIVATE_KEY }}
          script: cd ~/ && ./runner.sh