name: Deploy to Dev Server

# Trigger the workflow on push events to the 'dev' branch
on:
  push:
    branches:
      - dev # Change this if your development branch has a different name

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to project directory
            cd /var/www/qalb-service
            if [ $? -ne 0 ]; then
              echo "Directory doesn't exist, creating..."
              mkdir -p /var/www/qalb-service
              cd /var/www/qalb-service
              git clone https://github.com/Qalb-uz/qalb-service.git .
            fi

            # Make sure we're on dev branch
            git checkout dev

            # Pull latest changes
            echo "Pulling latest changes..."
            git pull origin dev

            # Build Docker image
            echo "Building Docker image..."
            docker build --platform linux/amd64 -t tenxegineer/qalb-service:dev .

            # Get current container ID if it exists
            CURRENT_CONTAINER=$(docker ps --filter "name=qalb-service" -q)

            # Start new container with docker-compose
            echo "Starting container..."
            docker-compose up -d

            # Wait for new container to be ready
            echo "Waiting for container to be ready..."
            sleep 5

            # Verify container is running
            NEW_CONTAINER=$(docker ps --filter "name=qalb-service" -q)
            if [ -z "$NEW_CONTAINER" ]; then
              echo "Container failed to start"
              exit 1
            fi

            # Clean up
            echo "Cleaning up..."
            docker image prune -f

            echo "Deployment successful!"
